name: tf
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pandas
  - notebook
  - matplotlib
  - nilearn
  - scikit-image
  - tensorflow-deps
  - pip:
      - tensorflow-macos
      - tensorflow-metal
      